version: '3.7'

services:
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        ports:
            - 5000:80
        volumes:
            - static_volume:/home/apps/qwerty/static
            - media_volume:/home/apps/qwerty/media
        depends_on:
            - web

    web:
        build:
            context: web
            dockerfile: Dockerfile
        command: /bin/sh entrypoint.sh
        env_file:
            - .env
        volumes:
            - ./web/:/home/apps/qwerty/
            - static_volume:/home/apps/qwerty/static
            - media_volume:/home/apps/qwerty/media
        expose:
            - 8000
        depends_on:
            - db
            - celery-worker

    celery-worker:
        build:
            context: web
            dockerfile: Dockerfile
        command: /bin/sh -c "sleep 10 && celery --workdir backend -A qwerty worker -l info"
        env_file:
            - .env
        volumes:
            - ./web/:/home/apps/qwerty/
        depends_on:
            - db
            - rabbitmq

    rabbitmq:
        image: "rabbitmq:latest"
        env_file:
            - .env
        ports:
            - "5672:5672"
            - "15672:15672"
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env

volumes:
  postgres_data:
  static_volume:
  media_volume:
